var vm = {
    "metadata": {
        "grandTotalEntities": 1,
        "totalEntities": 1,
        "filterCriteria": "",
        "sortCriteria": "",
        "page": 1,
        "count": 1,
        "startIndex": 1,
        "endIndex": 1
    },
    "entities": [
        {
            "vmId": "000567d5-213e-f854-39a7-64006a585477::31371713-5310-4dc7-8bc8-e006d35f86ea",
            "uuid": "31371713-5310-4dc7-8bc8-e006d35f86ea",
            "powerState": "on",
            "vmName": "ioana",
            "guestOperatingSystem": null,
            "ipAddresses": [],
            "hypervisorType": "kKvm",
            "hostName": "NTNX-c845db64-A",
            "hostId": "000567d5-213e-f854-39a7-64006a585477::5",
            "hostUuid": "22168d5c-fca2-47da-9147-4f1ca43059f0",
            "containerIds": null,
            "containerUuids": null,
            "nutanixVirtualDisks": null,
            "nutanixVirtualDiskIds": null,
            "nutanixVirtualDiskUuids": null,
            "virtualNicIds": [],
            "virtualNicUuids": [],
            "clusterUuid": "000567d5-213e-f854-39a7-64006a585477",
            "memoryCapacityInBytes": 2147483648,
            "memoryReservedCapacityInBytes": 2147483648,
            "numVCpus": 1,
            "cpuReservedInHz": null,
            "numNetworkAdapters": 0,
            "controlDomain": null,
            "vdiskNames": null,
            "vdiskFilePaths": null,
            "diskCapacityInBytes": null,
            "protectionDomainName": null,
            "protectionType": "unprotected",
            "consistencyGroupName": null,
            "description": "ioana",
            "fingerPrintOnWrite": null,
            "onDiskDedup": null,
            "stats": {
                "hypervisor_avg_io_latency_usecs": "0",
                "num_read_iops": "-1",
                "hypervisor_write_io_bandwidth_kBps": "0",
                "timespan_usecs": "-1",
                "controller_num_read_iops": "0",
                "controller.storage_tier.ssd.usage_bytes": "-1",
                "read_io_ppm": "-1",
                "controller_num_iops": "0",
                "hypervisor_memory_assigned_bytes": "-1",
                "total_read_io_time_usecs": "-1",
                "controller_total_read_io_time_usecs": "0",
                "hypervisor_num_io": "0",
                "controller_total_transformed_usage_bytes": "-1",
                "hypervisor_cpu_usage_ppm": "1677",
                "controller_num_write_io": "0",
                "avg_read_io_latency_usecs": "-1",
                "guest.memory_swapped_in_bytes": "0",
                "controller_total_io_time_usecs": "0",
                "memory_usage_ppm": "-1",
                "controller_total_read_io_size_kbytes": "0",
                "controller_num_seq_io": "-1",
                "controller_read_io_ppm": "0",
                "controller_total_io_size_kbytes": "0",
                "hypervisor.cpu_ready_time_ppm": "19",
                "controller_num_io": "0",
                "hypervisor_avg_read_io_latency_usecs": "0",
                "num_write_iops": "-1",
                "controller_num_random_io": "0",
                "num_iops": "-1",
                "guest.memory_usage_ppm": "-1",
                "hypervisor_num_read_io": "0",
                "hypervisor_total_read_io_time_usecs": "0",
                "controller_avg_io_latency_usecs": "0",
                "num_io": "-1",
                "controller_num_read_io": "0",
                "hypervisor_num_write_io": "0",
                "controller_seq_io_ppm": "-1",
                "guest.memory_usage_bytes": "-1",
                "controller_read_io_bandwidth_kBps": "0",
                "controller_io_bandwidth_kBps": "0",
                "hypervisor_num_received_bytes": "0",
                "hypervisor_timespan_usecs": "30000000",
                "hypervisor_num_write_iops": "0",
                "total_read_io_size_kbytes": "-1",
                "hypervisor_total_io_size_kbytes": "0",
                "avg_io_latency_usecs": "-1",
                "hypervisor_num_read_iops": "0",
                "hypervisor_swap_in_rate_kBps": "-1",
                "controller_write_io_bandwidth_kBps": "0",
                "controller_write_io_ppm": "0",
                "controller_user_bytes": "-1",
                "hypervisor_avg_write_io_latency_usecs": "0",
                "hypervisor_num_transmitted_bytes": "0",
                "hypervisor_total_read_io_size_kbytes": "0",
                "read_io_bandwidth_kBps": "-1",
                "guest.memory_swapped_out_bytes": "0",
                "hypervisor_memory_usage_ppm": "1000000",
                "hypervisor_num_iops": "0",
                "hypervisor_io_bandwidth_kBps": "0",
                "controller_num_write_iops": "0",
                "total_io_time_usecs": "-1",
                "controller_random_io_ppm": "-1",
                "controller.storage_tier.das-sata.usage_bytes": "-1",
                "controller_avg_read_io_size_kbytes": "0",
                "hypervisor_swap_out_rate_kBps": "-1",
                "total_transformed_usage_bytes": "-1",
                "avg_write_io_latency_usecs": "-1",
                "num_read_io": "-1",
                "write_io_bandwidth_kBps": "-1",
                "hypervisor_read_io_bandwidth_kBps": "0",
                "hypervisor_consumed_memory_bytes": "33484800",
                "random_io_ppm": "-1",
                "total_untransformed_usage_bytes": "-1",
                "hypervisor_total_io_time_usecs": "0",
                "num_random_io": "-1",
                "controller_avg_write_io_size_kbytes": "0",
                "controller_avg_read_io_latency_usecs": "0",
                "num_write_io": "-1",
                "total_io_size_kbytes": "-1",
                "controller.storage_tier.cloud.usage_bytes": "-1",
                "io_bandwidth_kBps": "-1",
                "controller_timespan_usecs": "30000000",
                "num_seq_io": "-1",
                "seq_io_ppm": "-1",
                "write_io_ppm": "-1",
                "controller_avg_write_io_latency_usecs": "0"
            },
            "usageStats": {
                "gpu_usage_ppm": "-1",
                "framebuffer_usage_ppm": "-1"
            },
            "nutanixGuestTools": {
                "vmId": "000567d5-213e-f854-39a7-64006a585477::31371713-5310-4dc7-8bc8-e006d35f86ea",
                "vmUuid": "31371713-5310-4dc7-8bc8-e006d35f86ea",
                "enabled": false,
                "applications": {
                    "vss_snapshot": false,
                    "file_level_restore": false
                },
                "toolsMounted": false,
                "installedVersion": null,
                "clusterVersion": null,
                "vmName": "ioana",
                "communicationLinkActive": false,
                "toRemove": false
            },
            "gpusInUse": null,
            "controllerVm": false,
            "displayable": true,
            "acropolisVm": true,
            "runningOnNdfs": true
        }
    ]
};

exports.newVm = function(vmName, hostUuid, clusterUuid, vmUuid, vmIp, vmMac) {

    var newVm = JSON.parse(JSON.stringify(vm.entities[0]));

    newVm.uuid = vmUuid;
    newVm.vmName = vmName;
    newVm.powerState = "on";
    newVm.ipAddresses = [vmIp];
    newVm.hostUuid = hostUuid;
    newVm.clusterUuid = clusterUuid;
    newVm.virtualNicIds = [ "000567d5-213e-f854-39a7-64006a585477::165679e1-eb7e-478b-8284-929f42247f72:" + vmMac];

    return newVm;
};
