var host = {
    "metadata": {
        "grand_total_entities": 1,
        "total_entities": 1,
        "filter_criteria": "",
        "sort_criteria": "",
        "page": 1,
        "count": 1,
        "start_index": 1,
        "end_index": 1
    },
    "entities": [
        {
            "service_vmid": "000567d5-213e-f854-39a7-64006a585477::6",
            "uuid": "e7034b83-97bc-4383-bfca-27c169d87b30",
            "disk_hardware_configs": {
                "1": {
                    "serial_number": "50014ee20a05c960",
                    "disk_id": "000567d5-213e-f854-39a7-64006a585477::41",
                    "disk_uuid": "6cd35e40-b8a0-48cb-8f80-d6733bcef34b",
                    "location": 1,
                    "bad": false,
                    "mounted": true,
                    "mount_path": "/home/nutanix/data/stargate-storage/disks/50014ee20a05c960",
                    "model": "WDC WD10EZEX-75M",
                    "vendor": "Not Available",
                    "boot_disk": false,
                    "only_boot_disk": false,
                    "under_diagnosis": false,
                    "background_operation": null,
                    "current_firmware_version": "2.5+",
                    "target_firmware_version": "2.5+",
                    "can_add_as_new_disk": false,
                    "can_add_as_old_disk": false
                },
                "2": {
                    "serial_number": "S39KNX0J631956F",
                    "disk_id": "000567d5-213e-f854-39a7-64006a585477::42",
                    "disk_uuid": "8a1c5395-eac9-4474-81d0-247d703e8063",
                    "location": 2,
                    "bad": false,
                    "mounted": true,
                    "mount_path": "/home/nutanix/data/stargate-storage/disks/S39KNX0J631956F",
                    "model": "Samsung SSD 850",
                    "vendor": "Not Available",
                    "boot_disk": true,
                    "only_boot_disk": false,
                    "under_diagnosis": false,
                    "background_operation": null,
                    "current_firmware_version": "2.5+",
                    "target_firmware_version": "2.5+",
                    "can_add_as_new_disk": false,
                    "can_add_as_old_disk": false
                },
                "3": null
            },
            "name": "NTNX-dec78c5d-A",
            "service_vmexternal_ip": "10.17.33.15",
            "oplog_disk_pct": 2.8,
            "oplog_disk_size": 32983355392,
            "hypervisor_key": "10.17.33.12",
            "hypervisor_address": "10.17.33.12",
            "hypervisor_username": "root",
            "hypervisor_password": null,
            "backplane_ip": null,
            "controller_vm_backplane_ip": "10.17.33.15",
            "rdma_backplane_ips": null,
            "management_server_name": "10.17.33.12",
            "ipmi_address": null,
            "ipmi_username": null,
            "ipmi_password": null,
            "monitored": true,
            "position": {
                "ordinal": 1,
                "name": "",
                "physical_position": null
            },
            "serial": "e7034b83-97bc-4383-bfca-27c169d87b30",
            "block_serial": "dec78c5d",
            "block_model": "UseLayout",
            "block_model_name": "CommunityEdition",
            "block_location": null,
            "host_maintenance_mode_reason": null,
            "hypervisor_state": "kAcropolisNormal",
            "metadata_store_status": "kNormalMode",
            "metadata_store_status_message": "Metadata store enabled on the node",
            "state": "NORMAL",
            "dynamic_ring_changing_node": null,
            "removal_status": [
                "NA"
            ],
            "vzone_name": "",
            "cpu_model": "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz",
            "num_cpu_cores": 4,
            "num_cpu_threads": 8,
            "num_cpu_sockets": 1,
            "cpu_frequency_in_hz": 3392000000,
            "cpu_capacity_in_hz": 13568000000,
            "memory_capacity_in_bytes": 33614200832,
            "hypervisor_full_name": "Nutanix 20180123.170",
            "hypervisor_type": "kKvm",
            "num_vms": 4,
            "boot_time_in_usecs": 1523236984077284,
            "is_degraded": false,
            "failover_cluster_fqdn": null,
            "failover_cluster_node_state": null,
            "reboot_pending": false,
            "default_vm_location": null,
            "default_vm_storage_container_id": null,
            "default_vm_storage_container_uuid": null,
            "default_vhd_location": null,
            "default_vhd_storage_container_id": null,
            "default_vhd_storage_container_uuid": null,
            "bios_version": null,
            "bios_model": null,
            "bmc_version": null,
            "bmc_model": null,
            "hba_firmwares_list": null,
            "cluster_uuid": "000567d5-213e-f854-39a7-64006a585477",
            "stats": {
                "hypervisor_avg_io_latency_usecs": "0",
                "num_read_iops": "70",
                "hypervisor_write_io_bandwidth_kBps": "0",
                "timespan_usecs": "20000000",
                "controller_num_read_iops": "0",
                "read_io_ppm": "451055",
                "controller_num_iops": "3",
                "total_read_io_time_usecs": "-1",
                "controller_total_read_io_time_usecs": "0",
                "hypervisor_num_io": "0",
                "controller_total_transformed_usage_bytes": "-1",
                "hypervisor_cpu_usage_ppm": "232638",
                "controller_num_write_io": "68",
                "avg_read_io_latency_usecs": "-1",
                "content_cache_logical_ssd_usage_bytes": "0",
                "controller_total_io_time_usecs": "134923",
                "controller_total_read_io_size_kbytes": "0",
                "controller_num_seq_io": "-1",
                "controller_read_io_ppm": "0",
                "content_cache_num_lookups": "213",
                "controller_total_io_size_kbytes": "888",
                "content_cache_hit_ppm": "877934",
                "controller_num_io": "68",
                "hypervisor_avg_read_io_latency_usecs": "0",
                "content_cache_num_dedup_ref_count_pph": "100",
                "num_write_iops": "85",
                "controller_num_random_io": "0",
                "num_iops": "156",
                "hypervisor_num_read_io": "0",
                "hypervisor_total_read_io_time_usecs": "0",
                "controller_avg_io_latency_usecs": "1984",
                "num_io": "3126",
                "controller_num_read_io": "0",
                "hypervisor_num_write_io": "0",
                "controller_seq_io_ppm": "-1",
                "controller_read_io_bandwidth_kBps": "0",
                "controller_io_bandwidth_kBps": "44",
                "hypervisor_num_received_bytes": "0",
                "hypervisor_timespan_usecs": "30701246",
                "hypervisor_num_write_iops": "0",
                "total_read_io_size_kbytes": "127987",
                "hypervisor_total_io_size_kbytes": "0",
                "avg_io_latency_usecs": "16053",
                "hypervisor_num_read_iops": "0",
                "content_cache_saved_ssd_usage_bytes": "0",
                "controller_write_io_bandwidth_kBps": "44",
                "controller_write_io_ppm": "1000000",
                "hypervisor_avg_write_io_latency_usecs": "0",
                "hypervisor_num_transmitted_bytes": "0",
                "hypervisor_total_read_io_size_kbytes": "0",
                "read_io_bandwidth_kBps": "6399",
                "hypervisor_memory_usage_ppm": "553952",
                "hypervisor_num_iops": "0",
                "hypervisor_io_bandwidth_kBps": "0",
                "controller_num_write_iops": "3",
                "total_io_time_usecs": "50183412",
                "content_cache_physical_ssd_usage_bytes": "0",
                "controller_random_io_ppm": "-1",
                "controller_avg_read_io_size_kbytes": "0",
                "total_transformed_usage_bytes": "-1",
                "avg_write_io_latency_usecs": "-1",
                "num_read_io": "1410",
                "write_io_bandwidth_kBps": "15262",
                "hypervisor_read_io_bandwidth_kBps": "0",
                "random_io_ppm": "-1",
                "total_untransformed_usage_bytes": "-1",
                "hypervisor_total_io_time_usecs": "0",
                "num_random_io": "-1",
                "controller_avg_write_io_size_kbytes": "13",
                "controller_avg_read_io_latency_usecs": "0",
                "num_write_io": "1716",
                "total_io_size_kbytes": "433239",
                "io_bandwidth_kBps": "21661",
                "content_cache_physical_memory_usage_bytes": "660673708",
                "controller_timespan_usecs": "20000000",
                "num_seq_io": "-1",
                "content_cache_saved_memory_usage_bytes": "0",
                "seq_io_ppm": "-1",
                "write_io_ppm": "548944",
                "controller_avg_write_io_latency_usecs": "1984",
                "content_cache_logical_memory_usage_bytes": "660673708"
            },
            "usage_stats": {
                "storage_tier.das-sata.usage_bytes": "88775655424",
                "storage.capacity_bytes": "954283505253",
                "storage.logical_usage_bytes": "223772491776",
                "storage_tier.das-sata.capacity_bytes": "860319497420",
                "storage.free_bytes": "776215459429",
                "storage_tier.ssd.usage_bytes": "89292390400",
                "storage_tier.ssd.capacity_bytes": "93964007833",
                "storage_tier.das-sata.free_bytes": "771543841996",
                "storage.usage_bytes": "178068045824",
                "storage_tier.ssd.free_bytes": "4671617433"
            },
            "has_csr": false,
            "host_nic_ids": [],
            "host_gpus": null,
            "gpu_driver_version": null,
            "key_management_device_to_certificate_status": {},
            "host_in_maintenance_mode": null
        }
    ]
};

exports.newHost = function (hostname, clusterUuid, hostUuid, hostIp) {
    var newHost = JSON.parse(JSON.stringify(host.entities[0]));

    newHost.name = hostname;
    newHost.cluster_uuid = clusterUuid;
    newHost.uuid = hostUuid;
    newHost.hypervisor_address = hostIp;

    return newHost;
};
